{"uid":"2b049b3ed1cd7e5f","name":"beforeMethod","fullName":"utils.run.BaseTest.beforeMethod","historyId":"62c3281338053d34322fe6efd096907c","time":{"start":1721666693768,"stop":1721666693768,"duration":0},"status":"broken","statusMessage":"java.lang.RuntimeException: Something went wrong while clearing dataio.restassured.internal.ValidatableResponseImpl@46ebd87a","statusTrace":"java.lang.RuntimeException: java.lang.RuntimeException: Something went wrong while clearing dataio.restassured.internal.ValidatableResponseImpl@46ebd87a\n\tat utils.run.ClearData.deleteHttp(ClearData.java:73)\n\tat utils.run.ClearData.deleteBills(ClearData.java:80)\n\tat utils.run.ClearData.clearData(ClearData.java:99)\n\tat utils.run.BaseTest.clearData(BaseTest.java:54)\n\tat utils.run.BaseTest.beforeMethod(BaseTest.java:74)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)\n\tat org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\n\tat org.testng.TestRunner.run(TestRunner.java:614)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)\nCaused by: java.lang.RuntimeException: Something went wrong while clearing dataio.restassured.internal.ValidatableResponseImpl@46ebd87a\n\tat utils.run.ClearData.deleteHttp(ClearData.java:68)\n\t... 41 more\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setUp","time":{"start":1721666681623,"stop":1721666691814,"duration":10191},"description":"","status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0}],"afterStages":[],"labels":[{"name":"package","value":"test.BillsTest"},{"name":"testClass","value":"test.BillsTest"},{"name":"testMethod","value":"beforeMethod"},{"name":"parentSuite","value":"Surefire suite"},{"name":"suite","value":"Surefire test"},{"name":"subSuite","value":"test.BillsTest"},{"name":"host","value":"fv-az1272-850"},{"name":"thread","value":"2954@fv-az1272-850.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"AS_ID","value":"-1"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":0,"unknown":0,"total":8},"items":[{"uid":"a11ac24bc6f17dd1","reportUrl":"https://Vlad1kek.github.io/Firefly_III_Test_Automation/108//#testresult/a11ac24bc6f17dd1","status":"broken","statusDetails":"java.lang.RuntimeException: Authorization does not work with token:","time":{"start":1721601637010,"stop":1721601637010,"duration":0}},{"uid":"e6de6d0614151c79","reportUrl":"https://Vlad1kek.github.io/Firefly_III_Test_Automation/107//#testresult/e6de6d0614151c79","status":"broken","statusDetails":"java.lang.RuntimeException: Authorization does not work with token:","time":{"start":1721600923599,"stop":1721600923600,"duration":1}},{"uid":"7f3b044b5f9438a","reportUrl":"https://Vlad1kek.github.io/Firefly_III_Test_Automation/106//#testresult/7f3b044b5f9438a","status":"broken","statusDetails":"java.lang.RuntimeException: Authorization does not work with token:","time":{"start":1721599102833,"stop":1721599102833,"duration":0}},{"uid":"bb1b03e604363545","reportUrl":"https://Vlad1kek.github.io/Firefly_III_Test_Automation/105//#testresult/bb1b03e604363545","status":"broken","statusDetails":"java.lang.RuntimeException: Authorization does not work with token:","time":{"start":1721598071532,"stop":1721598071532,"duration":0}},{"uid":"4793cb8843db7256","reportUrl":"https://Vlad1kek.github.io/Firefly_III_Test_Automation/104//#testresult/4793cb8843db7256","status":"broken","statusDetails":"java.lang.RuntimeException: Authorization does not work with token:","time":{"start":1721596041436,"stop":1721596041437,"duration":1}},{"uid":"b55b65ec77b7f8b9","reportUrl":"https://Vlad1kek.github.io/Firefly_III_Test_Automation/103//#testresult/b55b65ec77b7f8b9","status":"broken","statusDetails":"java.lang.RuntimeException: Authorization does not work with token:null","time":{"start":1721594892542,"stop":1721594892543,"duration":1}},{"uid":"d6a3f91a79bace8e","reportUrl":"https://Vlad1kek.github.io/Firefly_III_Test_Automation/101//#testresult/d6a3f91a79bace8e","status":"broken","statusDetails":"java.lang.NullPointerException: Cannot invoke \"com.fasterxml.jackson.databind.JsonNode.iterator()\" because \"dataNode\" is null","time":{"start":1721420876052,"stop":1721420876052,"duration":0}}]},"tags":[]},"source":"2b049b3ed1cd7e5f.json","parameterValues":[]}